// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYOYvZHuW8sbcug5MiQBllZmiDrJZ9WU',
    appId: '1:1063429083567:web:f0c209a0abb60c82825f5a',
    messagingSenderId: '1063429083567',
    projectId: 'fir-784ca',
    authDomain: 'fir-784ca.firebaseapp.com',
    storageBucket: 'fir-784ca.firebasestorage.app',
    measurementId: 'G-RQY84WKB23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAql11yB3VY5nuX0Gn2s-tdx0aV4w9PIg8',
    appId: '1:1063429083567:android:0a999d8e0fdd9a5b825f5a',
    messagingSenderId: '1063429083567',
    projectId: 'fir-784ca',
    storageBucket: 'fir-784ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnQ-FZ9l2O34Pbput0Mi8A77mbaqPAi7o',
    appId: '1:1063429083567:ios:128ad0c4fd6a914e825f5a',
    messagingSenderId: '1063429083567',
    projectId: 'fir-784ca',
    storageBucket: 'fir-784ca.firebasestorage.app',
    iosBundleId: 'com.example.myDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnQ-FZ9l2O34Pbput0Mi8A77mbaqPAi7o',
    appId: '1:1063429083567:ios:128ad0c4fd6a914e825f5a',
    messagingSenderId: '1063429083567',
    projectId: 'fir-784ca',
    storageBucket: 'fir-784ca.firebasestorage.app',
    iosBundleId: 'com.example.myDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUYOYvZHuW8sbcug5MiQBllZmiDrJZ9WU',
    appId: '1:1063429083567:web:496d3c422d43cfbe825f5a',
    messagingSenderId: '1063429083567',
    projectId: 'fir-784ca',
    authDomain: 'fir-784ca.firebaseapp.com',
    storageBucket: 'fir-784ca.firebasestorage.app',
    measurementId: 'G-J6MT9V55C2',
  );
}
